log:
  - name: root
    level: info
    formatter: '%d%T%m%n'
    appender:
      - type: FileLogAppender
        path: log.txt
      - type: StdoutLogAppender
  - name: system
    level: debug
    formatter: '%d%T%m%n'
    appender:
      - type: FileLogAppender
        path: log.txt
      - type: StdoutLogAppender
system:
  port: 9900
  value: 15
  vec:
    - 5
    - 6
    - 7
  list:
    - 5
    - 6
    - 7
  set: [5, 6, 7]
  uset: [5, 6, 7]
  map:
    k1: 3
    k2: 4
  umap:
    k1: 3
    k2: 4
